// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATyIyZ7mQC7RGAKSF3V5p3JJ7huNmS-O4',
    appId: '1:694428762149:web:309f5fc864a17d99e17fcc',
    messagingSenderId: '694428762149',
    projectId: 'amlogpresales',
    authDomain: 'amlogpresales.firebaseapp.com',
    databaseURL: 'https://amlogpresales-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'amlogpresales.appspot.com',
    measurementId: 'G-G7CZFX4KYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKZjQi0Qc4sy_sGgiHNpuLbw_IVt567UI',
    appId: '1:694428762149:android:03cbb9a8cef58758e17fcc',
    messagingSenderId: '694428762149',
    projectId: 'amlogpresales',
    databaseURL: 'https://amlogpresales-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'amlogpresales.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBllGFJ6mfUUKseFHUnjSfPKh-H5sNEceg',
    appId: '1:694428762149:ios:d90c9497627a20f3e17fcc',
    messagingSenderId: '694428762149',
    projectId: 'amlogpresales',
    databaseURL: 'https://amlogpresales-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'amlogpresales.appspot.com',
    iosClientId: '694428762149-qjp87hft08v9jb6n7536hs8cd5rmucfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBllGFJ6mfUUKseFHUnjSfPKh-H5sNEceg',
    appId: '1:694428762149:ios:d90c9497627a20f3e17fcc',
    messagingSenderId: '694428762149',
    projectId: 'amlogpresales',
    databaseURL: 'https://amlogpresales-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'amlogpresales.appspot.com',
    iosClientId: '694428762149-qjp87hft08v9jb6n7536hs8cd5rmucfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.proj1',
  );
}
